### ISSUE TITLE
cocotb tutorial updates (TODO)

### ISSUE THREAD

**Issue by rodrigomelo9** [rodrigomelo9/FOSS-for-FPGAs#17]
* [x] Add the TestFactory example.
* [x] Add how to read a generic/parameter (idem as a port)
* [x] Add how to PASS a failling test (expect_fail).
* [x] Add how to use timeouts (cocotb.test and with_timeout)
